### ISSUE TITLE
train

### ISSUE THREAD

**Issue by huangAoJiong** [Hedlen/MEFLUT#2]
How exactly does the code used to train my data set？

**Comment by huangAoJiong** [comment]
How to calculate the luts.txt of my exposure image sequence

**Comment by Hedlen** [comment]
@huangAoJiong Hi, Thanks for your attention to my work. I will update at a later time.

**Comment by huangAoJiong** [comment]
> @huangAoJiong Hi, Thanks for your attention to my work. I will update at a later time.

Well, look forward to your wonderful content.

**Comment by rxqH** [comment]
I look forward to hearing from you

> 嗨，感谢您对我工作的关注。我将在稍后更新。

我也十分期待您的回复

**Comment by konrad966** [comment]
@Hedlen Also looking forward for update with training code

**Comment by Hedlen** [comment]
@konrad966 @huangAoJiong @rxqH Thank you for your attention to my work. I apologize for the late update due to some things that happened some time ago.
